server:
  port: 8000


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 



spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE   # route id
          uri: lb://USER-SERVICE # destination url, register with eureka client, fetch url from eureka service registry
          predicates:
            - Path=/users/**    # incoming request url path
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**